version: "3.8"

services:
  postgres:
    image: postgres:13.1
    container_name: nestjs-database-connection-postgres-db
    restart: always
    environment:
      POSTGRES_USER: boghdady
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: online-courses-db
    volumes:
      - online-courses-db:/data/postgres
    ports:
      - 5434:5432

  adminer:
    image: adminer
    container_name: nestjs-database-connection-adminer
    restart: always
    ports: 
      - 8081:8080

volumes:
  online-courses-db: